# Generated by Django 5.0.6 on 2024-06-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0002_user_verification_token_alter_user_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=128, unique=True, verbose_name="email"
            ),
        ),
    ]
